### ISSUE TITLE
Process is not injecting to GammaRay with MingW

### ISSUE THREAD

**Issue by SUBRBHCONT** [KDAB/GammaRay#760] opened 2023-02-17 06:00 UTC
Setup:  Qt  6.2.4 
Cmake: 3.24.2

I have took the latest GammaRay code and tried building with Mingw compiler. The build was successful. But When I tried running the Gammaray Launcher getting the below error: 

Startup: gammaray-launcher
Qt Assistant not found in QT_INSTALL_BINS. Looking in standard Path next.
gammaray.qhc not found in "C:/Mahindra/GammaRay/build-GammaRay-Desktop_Qt_6_2_4_MinGW_64_bit-Debug/bin\\..//share/doc/GammaRay"  - help not available
Detaching: C:/Mahindra/GammaRay/build-GammaRay-Desktop_Qt_6_2_4_MinGW_64_bit-Debug/bin/gammaray.exe --no-inprocess --probe qt6_2-GNU-x86_64 --listen tcp://0.0.0.0 C:/Users/ZBHA1KOR/Desktop/build-test2-Desktop_Qt_6_2_4_MinGW_64_bit-Debug/HMI_Cluster_App.exe
Working Directory: C:/Users/ZBHA1KOR/Desktop/build-test2-Desktop_Qt_6_2_4_MinGW_64_bit-Debug

Do guide if I doing anything wrong here or any other additional setup or env paths need to be set for running the Gammaray Launcher. Thanks for the support in advance.

**Comment by Waqar144** [comment] 2023-03-01 08:08
How did you build gammaray? Can you share the cmake command used to configure?

**Comment by BhaSub1990** [comment] 2023-03-07 06:35
Below is the output of Cmake running through QTCreator:


__Running C:\Qt\Tools\CMake_64\bin\cmake.exe -S C:/Mahindra/GammaRay/GammaRay -B C:/Mahindra/GammaRay/build-GammaRay-Desktop_Qt_6_2_4_MinGW_64_bit-Release in C:\Mahindra\GammaRay\build-GammaRay-Desktop_Qt_6_2_4_MinGW_64_bit-Release.
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR) 
-- Could NOT find libbfd (missing: LIBDL_LIBRARY LIBDL_INCLUDE_DIR) 
-- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR) 
-- Building GammaRay 2.99.50 (revision: c5c2eb73a) in Release mode
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
-- Building probe for ABI: qt6_2-GNU-x86_64 (Release)
-- Could NOT find Wayland_Server (missing: Wayland_Server_LIBRARY Wayland_Server_INCLUDE_DIR) (found version "")
-- Could NOT find Wayland (missing: Wayland_LIBRARIES Server) (Required is at least version "1.12")
CMake Warning at cmake/ECM/find-modules/FindWayland.cmake:130 (message):
  Could not find wayland.xml in
Call Stack (most recent call first):
  plugins/wlcompositorinspector/CMakeLists.txt:14 (find_package)


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- qcollectiongenerator not found, documentation collection will not be generated.
-- The following features have been enabled:

 * Option GAMMARAY_BUILD_UI, Build the GammaRay client and in-process UI.
 * Option GAMMARAY_MULTI_BUILD, Build multiple applicable probe configurations.
 * Option GAMMARAY_BUILD_CLI_INJECTOR, Build command line injector on Windows.
 * Option GAMMARAY_BUILD_DOCS, Build GammaRay documentation.
 * Widget .ui file export, Requires QtDesigner library.
 * User Manual creation in qch format, Requires qdoc, qhelpgenerator, qtattributionsscanner, the qdoc templates and index files

-- The following OPTIONAL packages have been found:

 * Git
   Determine exact build version.
 * Qt6GuiTools (required version >= 6.2.4)
 * Qt6Gui
 * Qt6Network
 * Qt63DAnimation
 * Qt63DExtras
 * Qt63DInput
 * Qt63DLogic
 * Qt63DRender
 * Qt6QmlCompilerPlusTools (required version >= 6.2.4)
 * Qt6CoreTools (required version >= 6.2.4)
 * Qt6QmlCompilerPlus
 * Qt63DQuick
 * Qt6Bluetooth
 * Qt6Designer
 * Qt6OpenGL
 * Qt6Positioning
 * Qt6QmlTools (required version >= 6.2.4)
 * Qt6Qml
 * Qt6Quick
 * Qt6QuickWidgets
 * Qt6Svg
   Required for widget SVG export.
 * Qt6Test
 * Qt6ScxmlTools (required version >= 6.2.4)
 * Qt6Scxml (required version >= 5.8)
 * Qt6Help
 * Qt6LinguistTools
 * Qt6WidgetsTools (required version >= 6.2.4)
 * Qt6Widgets
 * QmlLint, <https://qt.io>
   Validate QML code.
 * PkgConfig

-- The following RECOMMENDED packages have been found:

 * Qt6Concurrent
   Required for the GammaRay launcher process list.

-- The following REQUIRED packages have been found:

 * Qt (required version >= 5.5)
 * Qt6, <https://qt.io/>

-- The following features have been disabled:

 * Option GAMMARAY_PROBE_ONLY_BUILD, Build only an additional probe configuration for an already existing launcher.
 * Option GAMMARAY_CLIENT_ONLY_BUILD, Build the client part only.
 * Option GAMMARAY_ENABLE_GPL_ONLY_FEATURES, Enable features only available under GPL license.
 * Option GAMMARAY_INSTALL_QT_LAYOUT, Install into Qt directory layout.
 * Option GAMMARAY_STATIC_PROBE, Build the probe as static library for compile-time injection.
 * Option GAMMARAY_ENFORCE_QT_ASSERTS, Force QT_ASSERT in all builds.
 * Option GAMMARAY_DISABLE_FEEDBACK, Disable user feedback support.
 * Option GAMMARAY_USE_PCH, Enable Precompiled Headers support
 * Option GAMMARAY_QT6_BUILD, Build with Qt6.
 * Option GAMMARAY_CORE_ONLY_LAUNCHER, Only use QtCore in the CLI launcher (breaks style injector, but is needed for Boot2Qt compatibility)
 * QtScript debugger, Requires QtScript and QtScriptTools.
 * ELF ABI detection, Automatic probe ABI detection on ELF-based systems. Requires elf.h.

-- The following OPTIONAL packages have not been found:

 * Qt6Location
 * Vulkan
 * WrapVulkanHeaders
 * Qt6Script
 * Qt6ScriptTools
 * Qt6WebEngineWidgets
 * Qt6WaylandCompositor
 * Qt6IviCore (required version >= 1.1)
 * Qt6IviVehicleFunctions (required version >= 1.1)
 * Qt6IviMedia (required version >= 1.1)
 * KF6CoreAddons, KDE KCoreAddons Framework, <https://www.kde.org/>
   Required for the KJob tracker plug-in.
 * Wayland (required version >= 1.12), C library implementation of the Wayland protocol: a protocol for a compositor to talk to its clients, <https://wayland.freedesktop.org/>
   Needed for the QtWayland compositor inspector plug-in.
 * Doxygen, API Documentation system, <https://www.doxygen.org>
   Needed to build the API documentation.

-- The following RECOMMENDED packages have not been found:

 * KF6SyntaxHighlighting (required version >= 5.28), <https://www.kde.org/>
   Syntax highlighting for code editor.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Mahindra/GammaRay/build-GammaRay-Desktop_Qt_6_2_4_MinGW_64_bit-Release
Elapsed time: 00:16._

**Comment by Waqar144** [comment] 2023-03-07 06:42
```
> Option GAMMARAY_QT6_BUILD, Build with Qt6.
```
Not sure if it will make a difference but can you try to enable `GAMMARAY_QT6_BUILD` and see if it changes anything.

Besides that, can you use a debugger to see what's happening? Perhaps GammaRay is crashing or something else.

**Comment by gitqic** [comment] 2023-05-19 11:35
Same here. The GammaRay built with Qt6 MinGW crashes when trying to attach a program. However, the GammaRay built with Qt6 MSVC 2019 works.

CMake command I used is (using msvc command prompt):

`cmake . -B build_msvc -DCMAKE_INSTALL_PREFIX=C:/Tools/gammaray_msvc -DCMAKE_PREFIX_PATH=c:/Qt/6.5.0/msvc2019_64 -DGAMMARAY_QT6_BUILD:BOOL=ON -DQMLLINT_IS_WORKING:BOOL=OFF`

A workaround has to be applied to avoid the qmllint issue, which is mentioned here: https://github.com/KDAB/GammaRay/issues/781

Comment out qml_lint(mapview.qml) in GammaRay/plugins/positioning/CMakeLists.txt (line 49)

**Comment by Waqar144** [comment] 2024-04-25 12:20
seems duplicate of #959

**Closed by Waqar144** 2024-04-25 12:20 UTC
Labels: bug
