### ISSUE TITLE
all custom render modes disabled for qt <= 5.6.0

### ISSUE THREAD

**Issue by gunrot** [KDAB/GammaRay#233] opened 2016-07-01 14:32 UTC
Subject is wrong, i mean **greater equal** 5.6.0
I noticed that all custom render modes are disabled. That was the my most favourite feature actually.

I enabled CustomRenderModeChanges | CustomRenderModeClipping | CustomRenderModeOverdraw
again for qt 5.6.1 windows 7

clipping did crash after a while once, but worked good enough for me.
Batches crashes directly.
I hope qt people will enable safe dynamic render mode switching for all modes again, once in a while working together with gammaray devs. 
meanwhile maybe also a cmake option could be added to enable this on own risk.

This is my patch :
````
--- a\/plugins/quickinspector/quickinspector.cpp
+++ b\/plugins/quickinspector/quickinspector.cpp
@@ -496,12 +496,14 @@

 void QuickInspector::checkFeatures()
 {
     emit features(
         Features(
-#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0) // FIXME any render mode crashes on first scene change
+#if QT_VERSION == QT_VERSION_CHECK(5, 6, 0) // FIXME any render mode crashes on first scene change
             NoFeatures
+#elif QT_VERSION >= QT_VERSION_CHECK(5, 6, 1) // batching crashes when enabled at runtime >= 5.5.0
+            CustomRenderModeChanges | CustomRenderModeClipping | CustomRenderModeOverdraw
 #elif QT_VERSION >= QT_VERSION_CHECK(5, 5, 0) // batching crashes when enabled at runtime >= 5.5.0
             CustomRenderModeChanges | CustomRenderModeClipping | CustomRenderModeOverdraw
 #elif QT_VERSION >= QT_VERSION_CHECK(5, 3, 0)
             AllCustomRenderModes
 #endif
````

**Comment by vkrause** [comment] 2016-07-01 14:36
It could be that the windows or the basic QSG render loops are less affected by this problem than the threaded one, that still crashes immediately with newer Qts when triggering this (on Linux).

**Comment by gunrot** [comment] 2016-07-01 16:39
i call qputenv("QSG_RENDER_LOOP", QByteArrayLiteral("threaded")
in main, before QGuiApplication constructor. That is supposed to activate the threaded render loop. I just checked in the debugger that it really does ;-).

**Comment by krf** [comment] 2016-07-05 20:22
Sorry, wrong issue, removing the label again. I think at this point it's the GammaRay devs who need to decide how to proceed here. Personally, I don't know about this particular feature, so I cannot tell.

**Comment by giucam** [comment] 2016-09-27 10:55
With b97e3c9 the issue is now fixed.

**Closed by giucam** 2016-09-27 10:55 UTC
Labels: enhancement
