### ISSUE TITLE
Cannot launch GammaRay on Windows 10

### ISSUE THREAD

**Issue by Austin1511** [KDAB/GammaRay#943] opened 2024-02-01 08:47 UTC
I built the GammaRay successfully on Windows10, but when I launch the application I got the error showed in the image.
<img width="349" alt="Snipaste_2024-02-01_16-43-58" src="https://github.com/KDAB/GammaRay/assets/23033823/40402c7c-1666-4464-9574-45348e6fd33a">

**Comment by mattkdab** [comment] 2024-02-07 19:31
@Austin1511 it's failing to load Qt dll's which probably means one of these two things:
1. it's possible that the dll's and the exe were built with different toolchains (eg mingw and msvc) that result in different name mangling
2. it's also possible that you have the wrong or multiple dll versions in your PATH

**Comment by Waqar144** [comment] 2024-04-25 12:18
seems duplicate of #959

**Closed by Waqar144** 2024-04-25 12:18 UTC
