### ISSUE TITLE
High load when using QCoreApplication

### ISSUE THREAD

**Issue by hcw70** [KDAB/GammaRay#115] opened 2015-03-25 10:50 UTC
When using QCoreApplication and starting with gammaray, the CPU load goes to 100% when switching to signal view.

The signal view shows contant emmiting signals from QEventDispatcherGLib.

Issue present with: Qt 5.3, and QT5.4 with latest gammaray from Git (2ea152dc3fc47aa38f3870535f09d0973203ebd4)

OS: Ubuntu 14.04

Window systems: Unity and Gnome3

The following code is used:

```
#include <QtCore/QtCore>

int main(int argc, char *argv[])
{
	QCoreApplication app(argc, argv);

	app.exec();
}
```
Regards

Hauke

**Comment by hcw70** [comment] 2015-03-30 07:17
A fix for this would be great since that allows gammaRay to inspect non-GUI applications.

**Comment by hcw70** [comment] 2015-09-11 11:49
Any news on this one?

**Comment by krf** [comment] 2015-11-24 21:55
I can't reproduce that; no high CPU load for me.

Using Kubuntu 15.10; Qt 5.4.2; latest Gammaray from master branch.

Is that still an issue for you? I can't think of a scenario which would cause high CPU load for you, to be honest.

**Comment by hcw70** [comment] 2015-11-25 08:56
It is no longer present. I have now tested with QT 5.5, and gammaray latest. Either it is fixed with newer QT version or with newer gammaray. 

Issue can be closed.

Regards 
Hauke

**Comment by krf** [comment] 2015-11-25 09:35
Thanks a lot for the feedback! Closing.

**Closed by krf** 2015-11-25 09:35 UTC
Labels: waiting for info
